Add adr for GUI implementation
MinBZK/ai-validation pull request #199
Opened 2024-09-05 08:52 UTC by rubenrouwhof

# Description

ADR for GUI implementation about NL Design System

## Checklist

Please check all the boxes that apply to this pull request using "x":

- [ ]  I have tested the changes locally and verified that they work as expected.
- [ ]  I have followed the project's coding conventions and style guidelines.
- [ ]  I have rebased my branch onto the latest commit of the main branch.
- [ ]  I have squashed or reorganized my commits into logical units.
- [ ]  I have read, understood and agree to the Developer Certificate of Origin below, which this project utilizes.

## Developer Certificate of Origin

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

2024-09-05 11:03 UTC, laurensWe reviewed
small remarks

2024-09-05 11:03 UTC, laurensWe commented on mkdocs.yml
> +        - projects/amt/reporting-standard/0.1a3.mds
```suggestion
        - projects/amt/reporting-standard/0.1a3.md
```

typo?

2024-09-05 11:03 UTC, laurensWe commented on docs/projects/amt/adrs/0007-front-end-components-implementation.md
> +We are planning to implement the NL Design System to ensure consistency, accessibility,
```suggestion
We implement the NL Design System to ensure consistency, accessibility,
```

2024-09-05 11:03 UTC, laurensWe commented on docs/projects/amt/adrs/0007-front-end-components-implementation.md
> +to align with accessibility standards and best practices, ensuring that our products are intuitive,
```suggestion
to align with accessibility standards and best practices of the government, ensuring that our products are intuitive,
```

2024-09-05 11:03 UTC, laurensWe commented on docs/projects/amt/adrs/0007-front-end-components-implementation.md
> +  in line with national standards.
```suggestion
  in line with governmental standards.
```

2024-09-05 12:27 UTC, anneschuth approved these changes
Small comments, lgtm

2024-09-09 12:29 UTC, GuusjeJuijn reviewed
LGTM some minor comments!

2024-09-09 12:29 UTC, GuusjeJuijn commented on docs/projects/amt/adrs/0007-front-end-components-implementation.md
> +We implement the NL Design System to ensure consistency, accessibility,
Maybe add a link to the NL design system webpage?

2024-09-09 12:29 UTC, GuusjeJuijn commented on docs/projects/amt/adrs/0007-front-end-components-implementation.md
> +we can streamline our design process, align with other governmental institutions. and avoid reinventing the wheel for common UI components.
, instead of .

2024-09-11 08:43 UTC, uittenbroekrobbert commented on docs/projects/amt/adrs/0007-front-end-components-implementation.md
> +## Positive
```suggestion
#### Positive
```

2024-09-11 08:45 UTC, uittenbroekrobbert reviewed
Can you adhere to the checklist requirements, like squash and tested locally etc, and mark completed where applicable?

2024-09-12 09:48 UTC, ChristopherSpelt submitted a review, later dismissed
LGTM

2024-09-12 09:48 UTC, ChristopherSpelt commented on docs/projects/amt/adrs/0007-front-end-components-implementation.md
> +we can streamline our design process, align with other governmental institutions. and avoid reinventing the wheel for common UI components.
I think you can even leave out the ,

2024-09-16 16:05 UTC, robbertbos requested changes
LGTM...but also left some suggestions

2024-09-16 16:05 UTC, robbertbos commented on docs/projects/amt/adrs/0007-front-end-components-implementation.md
> +
```suggestion
## Risks
```

2024-09-16 16:05 UTC, robbertbos commented on docs/projects/amt/adrs/0007-front-end-components-implementation.md
> +g be added as we progress).
```suggestion
* [NL Design System official documentation](https://nldesignsystem.nl/)
```

Or
```suggestion
* [NL Design System official documentation](https://nldesignsystem.nl/) and community resources (links to
  be added as we progress).
```

But I don't think we should add a "todo" in this ADR, so I would propose to use suggestion 1.

2024-09-17 15:11 UTC, rubenrouwhof commented on mkdocs.yml
> +        - projects/amt/adrs/0007-front-end-components-implementation.md
I did this because there was a problem with building the page, but that had another cause. So, i will revert the change.

2024-09-19 12:43 UTC, robbertbos approved these changes
LGMT. You became a git hero ;) One suggestion, but not a blocker.

2024-09-19 12:43 UTC, robbertbos commented on mkdocs.yml
> +        -  ... | flat | projects/amt/adrs/*
```suggestion
        - ... | flat | projects/amt/adrs/*
```

2024-09-19 12:53 UTC, robbertbos approved these changes

2024-09-19 12:53 UTC, merged