Add .editor config
MinBZK/ai-validation pull request #49
Opened 2024-03-06 09:34 UTC by berrydenhartog

# Description

Please include a summary of the changes and the related issue.

2024-03-06 09:54 UTC, uittenbroekrobbert commented
> # Description
> 
> Please include a summary of the changes and the related issue.

... is this PR missing the above information or is this not needed (just wondering).. the branch name suggets it adds an editorconfig, but it also included a dev container for running a (local?) (test?) mkdocs project.. so, looks good to me, but wondering about the PR comment :)

2024-03-06 11:09 UTC, berrydenhartog commented
Good catch @uittenbroekrobbert . Fixed the commits

2024-03-06 14:28 UTC, anneschuth requested changes

2024-03-06 14:28 UTC, anneschuth commented on .editorconfig
> +insert_final_newline = false
I'd set this to true

2024-03-06 14:28 UTC, anneschuth commented on .editorconfig
> +trim_trailing_whitespace = false
I'd set this to true

2024-03-06 14:28 UTC, anneschuth commented on .editorconfig
> +trim_trailing_whitespace = false
I'd set this to true

2024-03-07 08:11 UTC, berrydenhartog commented on .editorconfig
> +trim_trailing_whitespace = false
Done

2024-03-07 08:11 UTC, berrydenhartog commented on .editorconfig
> +insert_final_newline = false
Done

2024-03-07 08:11 UTC, berrydenhartog commented on .editorconfig
> +indent_style = space
Done

2024-03-07 08:12 UTC, berrydenhartog commented on .editorconfig
> +indent_size = 4
done

2024-03-07 08:12 UTC, berrydenhartog commented on .editorconfig
> +[*]
Done

2024-03-07 10:11 UTC, robbertbos approved these changes

2024-03-07 16:40 UTC, anneschuth approved these changes

2024-03-07 16:40 UTC, merged